WebTimeSheetManagement/Controllers/TaskassignedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTimeSheetManagement.Concrete;
using WebTimeSheetManagement.Filters;
using WebTimeSheetManagement.Interface;
using WebTimeSheetManagement.Models;
namespace WebTimeSheetManagement.Controllers
{
    public class TaskassignedController : Controller
    {
        ITaskassigned _ITaskassigned;
        IUsers _IUsers;
        public TaskassignedController()
        {
            _ITaskassigned = new TaskassignedConcrete();
            _IUsers = new UsersConcrete();
        }

        // GET: Task
        public ActionResult Add(int? TaskID)
        {
            try
            {
                if (TaskID == null)
                {

                }
                ViewBag.ModelHeading = "Assigned Employee";
                ViewBag.TaskID = TaskID;

                switch (Convert.ToInt16(Session["RoleID"]))
                {
                    case 1:
                        ViewBag.CurrentUser = Convert.ToInt32(Session["AdminUser"]);
                        break;
                    case 2:
                        ViewBag.CurrentUser = Convert.ToInt32(Session["UserID"]);
                        break;
                    case 3:
                        ViewBag.CurrentUser = Convert.ToInt32(Session["SuperAdmin"]);
                        break;
                    default:
                        break;
                }
                

                ViewBag.CurrentUserName = @Session["Username"];
                //ViewBag.EmployeeID = _IUsers.ShowallEmployeeUsers();
                return PartialView();
            }
            catch (Exception)
            {
                throw;
            }
        }

        public JsonResult ListofUsers()
        {
            try
            {
                var listofUsers = _IUsers.ShowallEmployeeUsers();
                return Json(listofUsers, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                throw;
            }
        }


        public ActionResult LoadTaskAssignedData(int TaskID)
        {
            var data = _ITaskassigned.ShowAssignedEmployeeForTasks(TaskID);

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult Add(TaskAssigned TaskAssigned)
        {
            if (ModelState.IsValid)
            {
                var result = _ITaskassigned.SaveAssignedTask(TaskAssigned);
                if (result > 0)
                {
                    TempData["EmployeeAssignedMessage"] = "Employee Assigned";
                    return Json(new {ID= result });
                }
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        // GET: Taskmaster
        public ActionResult Index()
        {

            return View();
        }


        public ActionResult LoadAssignedEmployeeForATask(int taskid)
        {
            var assigneddata = _ITaskassigned.ShowAssignedEmployeeForTasks(taskid);
            var data = assigneddata.ToList();
            return Json(new { rows = data }, JsonRequestBehavior.AllowGet);
        }

  
        public JsonResult Delete(string AssignedID, int TaskID, int UserID)
        {
            try
            {
                if (string.IsNullOrEmpty(Convert.ToString(AssignedID)))
                {
                    return Json("Error", JsonRequestBehavior.AllowGet);
                }

                var isExistsBurnHour = _ITaskassigned.CheckBurnHourExistsForEmployeeInATask(TaskID, UserID);

                if (isExistsBurnHour == false)
                {
                    var data = _ITaskassigned.TaskAssignedDelete(Convert.ToInt32(AssignedID));

                    if (data > 0)
                    {
                        return Json(data: true, behavior: JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json(data: false, behavior: JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    return Json(data: false, behavior: JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception)
            {
                throw;
            }
        }

    }
}

WebTimeSheetManagement/Views/Taskassigned/Add.cshtml
<div>
    <input type="hidden" id="CurrentTaskId" name="CurrentTaskId" value="@ViewBag.TaskID" />
    <input type="hidden" id="CurrentUser" name="CurrentUser" value="@ViewBag.CurrentUser" />
    <input type="hidden" id="CurrentUserName" name="CurrentUserName" value="@ViewBag.CurrentUserName" />
</div>


<div class="col-lg-12">
    <div class="panel panel-default">
        <div class="panel-heading">User Details</div>
        <div class="panel-body">
            @{
                if (Convert.ToInt16(Session["RoleID"]) == 1 )
                {
                    <div class="row">
                        <div class="form-group">
                            <div class="col-lg-6">
                                @Html.Label("Employee", new { @class = "manadatory" })
                                @Html.DropDownList("EmployeeID", new SelectList(string.Empty, "RegistrationID", "Name"), new { @class = "form-control" })
                            </div>

                            <div class="col-lg-6" style="position:relative; bottom:-25px">
                                <a href='#' class='btn btn-info' onclick='SaveEmployee();'>Assign</a>
                            </div>

                        </div>
                    </div>
                }
            }


     
            <table id="taskassign" class="table table-bordered" style="margin-top:10px;">
                <thead class="bg-danger text-center text-white">
                    <tr>
                        <th>User Name</th>
                        <th>Assigned date</th>
                        <th>Assigned By</th>
                        <th>Revoke</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</div>


<script>

    $(document).ready(function () {
        $.getJSON('@Url.Content("~/")' + "Taskassigned/ListofUsers", function (data) {
            var items1 = '';
            items1 += "<option value='" + "" + "'>" + "----Select----" + "</option>";
            $("#EmployeeID").empty();

            $.each(data, function (i, Employee) {
                items1 += "<option value='" + Employee.RegistrationID + "'>" + Employee.Name + "</option>";
            });
            $('#EmployeeID').html(items1);
        });


        function getAllData() {
            $.ajax({
                url: '@Url.Content("~/")' + "/Taskassigned/LoadTaskAssignedData",
                data: { TaskID: $('#CurrentTaskId').val() },
                dataType: "json",
                method: 'POST',
                success: function (data) {
                    for (var i = 0; i < data.length; i++) {
                        $("#taskassign").find("tbody").append($("<tr id='myTr" + data[i].TaskAssignedID + "'>")
                            .append($("<td style='display:none;'>").text(data[i].Userid))
                            .append($("<td>").text(data[i].UserName))
                            .append($("<td>").text(ToJavaScriptDate(data[i].Assigneddate)))
                            .append($("<td>").text(data[i].AssignedByName))
                            .append($("<td>").html("<a href='#' class='ui-icon ui-icon-circle-close' onclick='RevokeEmployee(" + data[i].TaskAssignedID + "," + $('#CurrentTaskId').val() + "," + data[i].Userid + ");' >Revoke</a>"))
                            );
                    }
                },
                error: function (err) {
                    console.log(err);
                }
            });
        }

        getAllData();
    });

    function ToJavaScriptDate(value) {
        var pattern = /Date\(([^)]+)\)/;
        var results = pattern.exec(value);
        var dt = new Date(parseFloat(results[1]));
        return dt.getDate() + "/" + (dt.getMonth() + 1) + "/" + dt.getFullYear();
    }



</script>


<script type="text/javascript">

    function GetCurrentDate() {
        var dt = new Date();
        return dt.getDate() + "/" + (dt.getMonth() + 1) + "/" + dt.getFullYear();
    }

    function Validate() {
        var t = 'N';
        $('#taskassign > tbody  > tr').each(function (index, tr) {
            if ($('#EmployeeID').val() == $(this).find('td').eq(0).text()) {
                t = "Found";
            }
        });

        return t;
    }


    function SaveEmployee() {

        if (Validate() == "Found") {
            alert("User already asigned");
            return false;
        }
        else {
            var TaskAssigned = {};
            TaskAssigned.Taskid = $('#CurrentTaskId').val();
            TaskAssigned.Userid = $('#EmployeeID').val();
            TaskAssigned.Assigneddate = new Date();
            TaskAssigned.Assignedby = $('#CurrentUser').val();

            $.ajax({
                url: '@Url.Action("Add", "Taskassigned")',
                type: 'post',
                data: '{TaskAssigned: ' + JSON.stringify(TaskAssigned) + '}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (d) {
                    $(function () {
                        $("#taskassign").find("tbody").append($("<tr id='myTr" + d.ID + "'>")
                            .append($("<td style='display:none;'>").text($('#EmployeeID').val()))
                            .append($("<td>").text($("#EmployeeID").find("option:selected").text()))
                            .append($("<td>").text(GetCurrentDate()))
                            .append($("<td>").text($('#CurrentUserName').val()))
                            .append($("<td>").html("<a href='#' class='ui-icon ui-icon-circle-close' onclick='RevokeEmployee(" + d.ID + "," + $('#CurrentTaskId').val() + "," + $('#EmployeeID').val() + ");' >Revoke</a>"))
                            );
                    });
                },
                error: function (xhr, textStatus, error) {
                    alert(xhr.statusText);
                    alert(textStatus);
                    alert(error);
                }
            });
        }
    }



    function RevokeEmployee(ID, TaskID, UserID) {
        if (confirm("Are you sure you want to Revoke assigned employee ...?")) {
            DeleteSheet(ID, TaskID, UserID);
        }
        else {
            return false;
        }
    }
    function DeleteSheet(ID, TaskID, UserID) {
        var url = '@Url.Content("~/")' + "Taskassigned/Delete";
        $.post(url, { AssignedID: ID, TaskID: TaskID, UserID: UserID }, function (data) {
            if (data) {
                $('#myTr' + ID).remove();
            }
            else {
                alert("Cannot be deleted it has Burn data entry!");
            }
        });
    }


</script>

WebTimeSheetManagement/Views/Taskassigned/Index.cshtml
@model IEnumerable<WebTimeSheetManagement.Models.TaskAssigned>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TaskMaster.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Userid)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Assigneddate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Assignedby)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TaskMaster.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Userid)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Assigneddate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Assignedby)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>